package dev.dheirav.thirsttrap.domain

// GENERATED FILE - do not edit by hand. Regenerate with tools/gen-catalogue.py.
//
// Sources, both public domain, both vendored under tools/ so a regeneration
// does not depend on either still being online:
//
//   biologiste95/plant-dataset (Unlicense) - 250 indoor plants with ordinal
//   codes for light, temperature, humidity, watering and soil mix.
//
//   ASPCA toxic and non-toxic plant list - pet toxicity.
//
// The dataset publishes no legend for its codes. The mapping was calibrated
// against plants whose care is not in dispute (Aloe and Crassula at the dry
// end, Adiantum and Fittonia at the wet end) and then cross-checked against the
// hand-written tier, which was written earlier and independently. See
// docs/SPECIES-CATALOGUE.md.
//
// These entries are deliberately thinner than the curated ones. They can say
// how bright, how wet and how humid, and nothing about what actually kills the
// plant - so they are marked CareDetail.BUNDLED and the UI says so.

/** The generated long tail. See [curatedSpeciesCatalogue] for the good stuff. */
val bundledSpeciesCatalogue: List<SpeciesCare> = listOf(

    SpeciesCare(
        name = "Chinese bellflower",
        botanical = "Abutilon",
        aliases = listOf("abutilon", "chinese bellflower", "flowering maple", "parlor maple"),
        light = "Prefers direct sun.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        note = "Prefers it on the cool side; dislikes a hot dry room.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Magic Flower",
        botanical = "Achimenes",
        aliases = listOf("achimenes", "magic flower", "hot water plant", "windows tears", "cupids bower"),
        light = "Prefers bright indirect light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Sweet Flag",
        botanical = "Acorus calamus",
        aliases = listOf("acorus calamus", "sweet flag"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Miniature Sweet Flag",
        botanical = "Acorus gramineus",
        aliases = listOf("acorus gramineus", "miniature sweet flag"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Crinkle-Leaf Plant",
        botanical = "Adromischus cristatus",
        aliases = listOf("adromischus cristatus", "crinkle leaf plant"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        note = "Wants a free-draining, gritty mix.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Plover Eggs",
        botanical = "Adromischus cooperi",
        aliases = listOf("adromischus festivus", "adromischus cooperi", "plover eggs"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        note = "Wants a free-draining, gritty mix. Older name: Adromischus festivus. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Royal Wine Bromeliad",
        botanical = "Aechmea",
        aliases = listOf("aechmea", "royal wine bromeliad"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Silver Vase",
        botanical = "Aechmea fasciata",
        aliases = listOf("aechmea fasciata", "silver vase"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Purplish Coral Berry",
        botanical = "Aechmea miniata",
        aliases = listOf("aechmea miniata", "purplish coral berry"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Zebra Basket Vine",
        botanical = "Aeschynanthus longicaulis",
        aliases = listOf("aeschynanthus marmoratus", "aeschynanthus longicaulis", "zebra basket vine"),
        light = "Prefers bright indirect light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        note = "Older name: Aeschynanthus marmoratus. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Lipstick Vine",
        botanical = "Aeschynanthus pulcher",
        aliases = listOf("aeschynanthus pulcher", "lipstick vine"),
        light = "Prefers bright indirect light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Queen Agave",
        botanical = "Agave victoriae-reginae",
        aliases = listOf("agave victoriae reginae", "queen agave", "agave"),
        light = "Prefers direct sun.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        note = "Wants a free-draining, gritty mix.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Allamanda",
        botanical = "Allamanda cathartica",
        aliases = listOf("allamanda cathartica", "allamanda"),
        light = "Prefers direct sun.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Wants humidity above ordinary room air. Suffers in dry winter heating.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Miniature Pouch Flower",
        botanical = "Pachycaulos nummularia",
        aliases = listOf("alloplectus nummularia", "pachycaulos nummularia", "miniature pouch flower"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Wants humidity above ordinary room air. Suffers in dry winter heating.",
        note = "Older name: Alloplectus nummularia. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Pineapple",
        botanical = "Ananas comosus",
        aliases = listOf("ananas comosus", "pineapple", "ananas"),
        light = "Prefers direct sun, and tolerates down to bright indirect light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Zebra Plant",
        botanical = "Aphelandra squarrosa",
        aliases = listOf("aphelandra squarrosa", "aphelandra"),
        light = "Prefers bright indirect light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Caladium",
        botanical = "Araliaceae",
        aliases = listOf("araliaceae", "caladium"),
        light = "Prefers bright indirect light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Wants humidity above ordinary room air. Suffers in dry winter heating.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Norfolk Island Pine",
        botanical = "Araucaria heterophylla",
        aliases = listOf("araucaria heterophylla", "norfolk island pine", "araucaria"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Ardisia",
        botanical = "Ardissa crenata",
        aliases = listOf("ardissa crenata", "ardisia", "ardissa"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Bird's Nest Fern",
        botanical = "Asokebuyn budys",
        aliases = listOf("asokebuyn budys", "birds nest fern", "asokebuyn"),
        light = "Prefers medium light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        note = "Wants a moisture-retentive, peaty mix.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Sickle Thorn",
        botanical = "Asparagus falcatus",
        aliases = listOf("asparagus falcatus", "sickle thorn", "asparagus"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Cast Iron Plant",
        botanical = "Aspidistra elatior",
        aliases = listOf("aspidistra elatior", "cast iron plant", "aspidistra"),
        light = "Prefers medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Happy in dry air.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Mother Fern",
        botanical = "Asplenium daucifolium",
        aliases = listOf("asplenium daucifolium", "mother fern", "asplenium"),
        light = "Prefers medium light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        note = "Wants a moisture-retentive, peaty mix.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Bishop's Cap",
        botanical = "Astrophytum myriostigma",
        aliases = listOf("astrophytum myriostigma", "bishops cap", "astrophytum"),
        light = "Prefers bright indirect light.",
        water = "Let the pot dry out almost completely between waterings.",
        medium = Medium.SOIL,
        depletionTrigger = 0.75,
        humidity = "Happy in dry air.",
        note = "Wants a free-draining, gritty mix.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Ponytail",
        botanical = "Beaucarnea recurvata",
        aliases = listOf("beaucarnea recurvata", "ponytail", "beaucarnea"),
        light = "Prefers direct sun.",
        water = "Let the pot dry out almost completely between waterings.",
        medium = Medium.SOIL,
        depletionTrigger = 0.75,
        humidity = "Happy in dry air.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        note = "Wants a free-draining, gritty mix.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Justicia brandegeeana",
        botanical = "Justicia brandegeeana",
        aliases = listOf("beloperone guttata", "justicia brandegeeana", "justicia"),
        light = "Prefers bright indirect light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        note = "Older name: Beloperone guttata. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Queen's Tears",
        botanical = "Billbergia nutans",
        aliases = listOf("billbergia nutans", "queens tears"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Urn Plant",
        botanical = "Billbergia pyramidalis",
        aliases = listOf("billbergia pyramidalis", "urn plant"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Bougainvillea",
        botanical = "Bougainvillea spp.",
        aliases = listOf("bougainvillea spp", "bougainvillea"),
        light = "Prefers direct sun.",
        water = "Let the pot dry out almost completely between waterings.",
        medium = Medium.SOIL,
        depletionTrigger = 0.75,
        humidity = "Happy in dry air.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Schefflera",
        botanical = "Heptapleurum actinophyllum",
        aliases = listOf("brassaia actinophylla", "heptapleurum actinophyllum", "schefflera"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this species.)",
        note = "Older name: Brassaia actinophylla. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Dwarf Schefflera",
        botanical = "Brassaia arboricola",
        aliases = listOf("brassaia arboricola", "dwarf schefflera"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Slipperwort",
        botanical = "Calceolaria crenatiflora",
        aliases = listOf("calceolaria crenatiflora", "slipperwort", "calceolaria"),
        light = "Prefers bright indirect light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Wants humidity above ordinary room air. Suffers in dry winter heating.",
        note = "Prefers it on the cool side; dislikes a hot dry room.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Bonsai Natal Plum",
        botanical = "Carissa macrocarpa",
        aliases = listOf("carissa grandiflora", "carissa macrocarpa", "bonsai natal plum", "boxwood beauty", "carissa"),
        light = "Prefers direct sun, and tolerates down to bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        note = "Older name: Carissa grandiflora. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Fishtail Palm",
        botanical = "Caryota mitis",
        aliases = listOf("caryota mitis", "fishtail palm", "caryota"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Madagascar Periwinkle",
        botanical = "Catharanthus roseus",
        aliases = listOf("catharanthus roseus", "madagascar periwinkle", "catharanthus"),
        light = "Prefers direct sun, and tolerates down to bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Wants humidity above ordinary room air. Suffers in dry winter heating.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Parlor Palm",
        botanical = "Chamaedorea elegans",
        aliases = listOf("chamaedorea elegans", "parlor palm"),
        light = "Prefers medium light, and tolerates down to low light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Bamboo Palm",
        botanical = "Chamaedorea seifrizii",
        aliases = listOf("chamaedorea erumpens", "chamaedorea seifrizii", "bamboo palm"),
        light = "Prefers medium light, and tolerates down to low light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        note = "Older name: Chamaedorea erumpens. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "European Fan Palm",
        botanical = "Chamaerops humilis",
        aliases = listOf("chamaerops humilis", "european fan palm", "chamaerops"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Hindustan Gentian",
        botanical = "Microchirita lavandulacea",
        aliases = listOf("chirita lavandulacea", "microchirita lavandulacea", "hindustan gentian"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Wants humidity above ordinary room air. Suffers in dry winter heating.",
        note = "Older name: Chirita lavandulacea. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Chrysanthemum",
        botanical = "Chrysanthemum morifolium",
        aliases = listOf("chrysanthemum morifolium", "chrysanthemum"),
        light = "Prefers direct sun.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Kangaroo Vine",
        botanical = "Cissus antarctica",
        aliases = listOf("cissus antarctica", "kangaroo vine"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Wax Cissus",
        botanical = "Cissus rotundifolia",
        aliases = listOf("cissus rotundifolia", "wax cissus"),
        light = "Prefers bright indirect light.",
        water = "Let the pot dry out almost completely between waterings.",
        medium = Medium.SOIL,
        depletionTrigger = 0.75,
        humidity = "Happy in dry air.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Calamondin Orange",
        botanical = "Citrus microcarpa",
        aliases = listOf("citrofortunella mitis", "citrus microcarpa", "calamondin orange"),
        light = "Prefers direct sun, and tolerates down to bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        note = "Prefers it on the cool side; dislikes a hot dry room. Older name: Citrofortunella mitis. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Clerodendrum thomsoniae",
        botanical = "Clerodendrum thomsoniae",
        aliases = listOf("clerodendrum thomsoniae", "clerodendrum"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        note = "Prefers it on the cool side; dislikes a hot dry room.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Kafir Lily",
        botanical = "Clivia miniata",
        aliases = listOf("clivia miniata", "kafir lily", "clivia"),
        light = "Prefers bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Coffee",
        botanical = "Coffeaa arabica",
        aliases = listOf("coffeaa arabica", "coffee", "coffeaa"),
        light = "Prefers bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Goldfish Plant",
        botanical = "Colummea",
        aliases = listOf("colummea", "goldfish plant"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Wants humidity above ordinary room air. Suffers in dry winter heating.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Cordyline australis",
        botanical = "Cordyline australis",
        aliases = listOf("cordyline australis"),
        light = "Prefers bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this species.)",
        note = "Prefers it on the cool side; dislikes a hot dry room.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Ti Plant",
        botanical = "Cordyline fruticosa",
        aliases = listOf("cordyline terminalis", "cordyline fruticosa", "ti plant"),
        light = "Prefers bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this species.)",
        note = "Prefers it on the cool side; dislikes a hot dry room. Older name: Cordyline terminalis. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Crossandra",
        botanical = "Crossandra infundibuliformis",
        aliases = listOf("crossandra infundibuliformis", "crossandra"),
        light = "Prefers bright indirect light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Dwarf Rose Stripe Star",
        botanical = "Cryptanthus bivittatus",
        aliases = listOf("cryptanthus bivittatus", "dwarf rose stripe star"),
        light = "Prefers bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Stiff Pheasant Leaf",
        botanical = "Cryptanthus zonatus",
        aliases = listOf("cryptanthus fosteranus", "cryptanthus zonatus", "stiff pheasant leaf"),
        light = "Prefers bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        note = "Older name: Cryptanthus fosteranus. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "House Holly Fern",
        botanical = "Cyrtomium falcatum",
        aliases = listOf("cyrtomium falcatum", "house holly fern", "cyrtomium"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        note = "Wants a moisture-retentive, peaty mix.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Rabbit's Foot Fern",
        botanical = "Davallia fejeensis",
        aliases = listOf("davallia fejeensis", "rabbits foot fern", "davallia"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Wants humidity above ordinary room air. Suffers in dry winter heating.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Exotica Perfection",
        botanical = "Dieffenbachia",
        aliases = listOf("dieffenbachia", "exotica perfection"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this species.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Flame Violet",
        botanical = "Episcia cupreata",
        aliases = listOf("episcia cupreata", "flame violet"),
        light = "Prefers bright indirect light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Wants humidity above ordinary room air. Suffers in dry winter heating.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Lace-Flower Vine",
        botanical = "Alsobia dianthiflora",
        aliases = listOf("episcia dianthiflora", "alsobia dianthiflora", "lace flower vine"),
        light = "Prefers bright indirect light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Wants humidity above ordinary room air. Suffers in dry winter heating.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        note = "Older name: Episcia dianthiflora. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Scarlet Violet",
        botanical = "Episcia reptans",
        aliases = listOf("episcia reptans", "scarlet violet"),
        light = "Prefers bright indirect light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Wants humidity above ordinary room air. Suffers in dry winter heating.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Crown-of-Thorns",
        botanical = "Euphorbia milii",
        aliases = listOf("euphorbia milii", "crown of thorns"),
        light = "Prefers direct sun.",
        water = "Let the pot dry out almost completely between waterings.",
        medium = Medium.SOIL,
        depletionTrigger = 0.75,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this genus.)",
        note = "Wants a free-draining, gritty mix.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Poinsettia",
        botanical = "Euphorbia pulcherrima",
        aliases = listOf("euphorbia pulcherrima", "poinsettia"),
        light = "Prefers direct sun, and tolerates down to bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this species.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Milkbush",
        botanical = "Euphorbia tirucalli",
        aliases = listOf("euphorbia tirucalli", "milkbush"),
        light = "Prefers direct sun, and tolerates down to bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this species.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Botanical Wonder Plant",
        botanical = "Fatshedera lizei",
        aliases = listOf("fatshedera lizei", "botanical wonder plant", "fatshedera"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        note = "Prefers it on the cool side; dislikes a hot dry room.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Weeping Fig",
        botanical = "Ficus benjamina",
        aliases = listOf("ficus benjamina", "weeping fig"),
        light = "No light level recorded for this one - treat bright indirect as the safe default.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this species.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Mistletoe Ficus",
        botanical = "Ficus deltoidea",
        aliases = listOf("ficus deltoidea", "mistletoe ficus"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Cuban Laurel",
        botanical = "Ficus retusa",
        aliases = listOf("ficus retusa", "cuban laurel"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Rooting Fig",
        botanical = "Ficus sagittata",
        aliases = listOf("ficus sagittata", "rooting fig"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Fuchsias",
        botanical = "Fuchsia hybrida",
        aliases = listOf("fuchsia hybrida", "fuchsias"),
        light = "Prefers bright indirect light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Wants humidity above ordinary room air. Suffers in dry winter heating.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        note = "Prefers it on the cool side; dislikes a hot dry room.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Ox Tongue",
        botanical = "Gasteria hybrida",
        aliases = listOf("gasteria hybrida", "ox tongue", "gasteria"),
        light = "Prefers bright indirect light.",
        water = "Let the pot dry out almost completely between waterings.",
        medium = Medium.SOIL,
        depletionTrigger = 0.75,
        humidity = "Ordinary room air is fine.",
        note = "Wants a free-draining, gritty mix.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Jewel Leaf Plant",
        botanical = "Graptopetalum amethystinum",
        aliases = listOf("graptopetalum amethystinum", "jewel leaf plant", "graptopetalum"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the pot dry out almost completely between waterings.",
        medium = Medium.SOIL,
        depletionTrigger = 0.75,
        humidity = "Ordinary room air is fine.",
        note = "Wants a free-draining, gritty mix.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Scarlet Star",
        botanical = "Guzmania lingulata",
        aliases = listOf("guzmania lingulata", "scarlet star"),
        light = "Prefers bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Wants humidity above ordinary room air. Suffers in dry winter heating.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Striped Torch",
        botanical = "Guzmania monostachia",
        aliases = listOf("guzmania monostachia", "striped torch"),
        light = "Prefers bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Wants humidity above ordinary room air. Suffers in dry winter heating.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Purple Passion",
        botanical = "Gynura aurantiaca",
        aliases = listOf("gynura aurantiaca", "purple passion or gynura sarmentosa", "gynura"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Waffle Plant",
        botanical = "Strobilanthes alternata",
        aliases = listOf("hemigraphis alternata", "strobilanthes alternata", "waffle plant", "strobilanthes"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        note = "Older name: Hemigraphis alternata. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Chinese Hibiscus",
        botanical = "Hibiscus rosa-sinensis",
        aliases = listOf("hibiscus rosa sinensis", "chinese hibiscus", "hibiscus"),
        light = "Prefers direct sun.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Amaryllis",
        botanical = "Hippeastrum",
        aliases = listOf("hippeastrum", "amaryllis"),
        light = "Prefers bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Belmore Sentry Palm",
        botanical = "Howea belmoreana",
        aliases = listOf("howea belmoreana", "belmore sentry palm"),
        light = "Prefers medium light, and tolerates down to low light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Kentia Palm",
        botanical = "Howea forsterana",
        aliases = listOf("howea forsterana", "kentia palm"),
        light = "Prefers bright indirect light, and tolerates down to low light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Hyacinth",
        botanical = "Hyacinthus orientalis",
        aliases = listOf("hyacinthus orientalis", "hyacinth", "hyacinthus"),
        light = "Prefers bright indirect light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this species.)",
        note = "Prefers it on the cool side; dislikes a hot dry room.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Busy Lizzie Impatiens",
        botanical = "Impatiens walleriana",
        aliases = listOf("impatiens wallerana", "impatiens walleriana", "busy lizzie impatiens", "impatiens"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        note = "Older name: Impatiens wallerana. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Ixora",
        botanical = "Ixora coccinea",
        aliases = listOf("ixora coccinea", "ixora"),
        light = "Prefers direct sun.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Peregrian",
        botanical = "Jatropha integerrima",
        aliases = listOf("jatropha integerrima", "peregrian", "jatropha"),
        light = "Prefers direct sun.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Shrimp Plant",
        botanical = "Justicia brandegeana",
        aliases = listOf("justicia brandegeana", "shrimp plant"),
        light = "Prefers direct sun, and tolerates down to bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Turk's Cap",
        botanical = "Malvaviscus arboreus",
        aliases = listOf("malvaviscus arboreus", "turks cap", "malvaviscus"),
        light = "Prefers direct sun.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Powder Puff",
        botanical = "Mammillaria bocasana",
        aliases = listOf("mammillaria bocasana", "powder puff", "mammillaria"),
        light = "Prefers direct sun, and tolerates down to bright indirect light.",
        water = "Let the pot dry out almost completely between waterings.",
        medium = Medium.SOIL,
        depletionTrigger = 0.75,
        humidity = "Happy in dry air.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        note = "Wants a free-draining, gritty mix.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Firecracker Plant",
        botanical = "Manettia paraguariensis",
        aliases = listOf("manettia inflata", "manettia paraguariensis", "firecracker plant", "manettia"),
        light = "Prefers bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Wants humidity above ordinary room air. Suffers in dry winter heating.",
        note = "Older name: Manettia inflata. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Plush Vine",
        botanical = "Mikania ternata",
        aliases = listOf("mikania ternata", "plush vine", "mikania"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Black Alloplectus",
        botanical = "Nautilocalyx lynchii",
        aliases = listOf("nautilocalyx lynchii", "black alloplectus", "nautilocalyx"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Tricolor Bromeliad",
        botanical = "Neoregelia carolinae",
        aliases = listOf("neoregelia carolinae", "tricolor bromeliad"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Fingernail Plant",
        botanical = "Neoregelia spectabilis",
        aliases = listOf("neoregelia spectabilis", "fingernail plant"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Zonata",
        botanical = "Neoregelia zonata",
        aliases = listOf("neoregelia zonata", "zonata"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Miniature Bird's Nest",
        botanical = "Nidularium innocentii",
        aliases = listOf("nidularium innocentii", "miniature birds nest", "nidularium"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Irish Mittens",
        botanical = "Opuntia vulgaris",
        aliases = listOf("opuntia vulgaris", "irish mittens", "opuntia"),
        light = "Prefers direct sun, and tolerates down to bright indirect light.",
        water = "Let the pot dry out almost completely between waterings.",
        medium = Medium.SOIL,
        depletionTrigger = 0.75,
        humidity = "Happy in dry air.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        note = "Wants a free-draining, gritty mix.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Yellow Shrimp Plant",
        botanical = "Pachystachys lutea",
        aliases = listOf("pachystachys lutea", "yellow shrimp plant", "pachystachys"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Pelargonium grandiflorum",
        botanical = "Pelargonium grandiflorum",
        aliases = listOf("pelargonium grandiflorum", "pelargonium"),
        light = "Prefers direct sun, and tolerates down to bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this genus.)",
        note = "Prefers it on the cool side; dislikes a hot dry room.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Egyptian Star Cluster",
        botanical = "Pentas lanceolata",
        aliases = listOf("pentas lanceolata", "egyptian star cluster", "pentas"),
        light = "Prefers direct sun.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Pigmy Date Palm",
        botanical = "Phoenix roebelenii",
        aliases = listOf("phoenix roebelenii", "pigmy date palm", "phoenix"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Staghorn Fern",
        botanical = "Platycerium bifurcatum",
        aliases = listOf("platycerium bifurcatum", "staghorn fern", "platycerium"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        note = "Wants a moisture-retentive, peaty mix.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Podocarpus",
        botanical = "Podocarpus macrophyllus",
        aliases = listOf("podocarpus macrophyllus", "podocarpus"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Lady Palm",
        botanical = "Rhapis excelsa",
        aliases = listOf("rhapis excelsa", "lady palm", "rhapis"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Azaleas",
        botanical = "Rhododendron",
        aliases = listOf("rhododendron", "azaleas"),
        light = "Prefers bright indirect light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Wants humidity above ordinary room air. Suffers in dry winter heating.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this genus.)",
        note = "Prefers it on the cool side; dislikes a hot dry room.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Red-Spray Ruellia",
        botanical = "Ruellia graeciznas",
        aliases = listOf("ruellia graeciznas", "red spray ruellia", "ruellia"),
        light = "Prefers direct sun, and tolerates down to bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "African Violets",
        botanical = "Saintpaulia",
        aliases = listOf("saintpaulia", "african violets"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Keep the mix lightly moist. Let the surface dry, but do not let the pot dry through.",
        medium = Medium.SOIL,
        depletionTrigger = 0.35,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Strawberry Geranium",
        botanical = "Saxifraga stolonifera",
        aliases = listOf("saxifraga stolonifera", "strawberry geranium", "saxifraga"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        note = "Prefers it on the cool side; dislikes a hot dry room.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Scheflera actinophylla",
        botanical = "Scheflera actinophylla",
        aliases = listOf("scheflera actinophylla", "scheflera"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Gloxinia",
        botanical = "Sinningia speciosa",
        aliases = listOf("sinningia speciosa", "gloxinia", "sinningia"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Wants humidity above ordinary room air. Suffers in dry winter heating.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Stephanotis floribunda",
        botanical = "Stephanotis floribunda",
        aliases = listOf("stephanotis floribunda", "stephanotis"),
        light = "Prefers bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this species.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Cape Primrose",
        botanical = "Streptocarpus",
        aliases = listOf("streptocarpus", "cape primrose"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Persian Shield",
        botanical = "Strobilanthes auriculata",
        aliases = listOf("strobilanthes dyeranum", "strobilanthes auriculata", "persian shield"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        note = "Older name: Strobilanthes dyeranum. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Piggyback Plant",
        botanical = "Tolmiea menziesii",
        aliases = listOf("tolmiea menziesii", "piggyback plant", "tolmiea"),
        light = "Prefers bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        note = "Prefers it on the cool side; dislikes a hot dry room.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Dancing Bulb",
        botanical = "Trillandsia bulbosa",
        aliases = listOf("trillandsia bulbosa", "dancing bulb", "trillandsia"),
        light = "Prefers bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Flaming Sword",
        botanical = "Lutheria splendens",
        aliases = listOf("vriesea splendens", "lutheria splendens", "flaming sword"),
        light = "Prefers bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        note = "Older name: Vriesea splendens. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "Spineless Yucca",
        botanical = "Yucca gigantea",
        aliases = listOf("yucca elephantipes", "yucca gigantea", "spineless yucca", "yucca"),
        light = "Prefers bright indirect light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Happy in dry air.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this genus.)",
        note = "Older name: Yucca elephantipes. Still what most labels say.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "cyperus alternifolius",
        botanical = "cyperus alternifolius",
        aliases = listOf("cyperus alternifolius", "cyperus"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "dieffenbachia amoena",
        botanical = "dieffenbachia amoena",
        aliases = listOf("dieffenbachia amoena"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Toxic to cats and dogs. (ASPCA, this species.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

    SpeciesCare(
        name = "fuchsia leonora",
        botanical = "fuchsia leonora",
        aliases = listOf("fuchsia leonora"),
        light = "Prefers bright indirect light, and tolerates down to medium light.",
        water = "Let the top third to half of the pot dry out before watering.",
        medium = Medium.SOIL,
        depletionTrigger = 0.5,
        humidity = "Ordinary room air is fine.",
        toxicity = "Not toxic to cats and dogs. (ASPCA, this genus.)",
        detail = CareDetail.BUNDLED,
        source = "plant-dataset (Unlicense); ASPCA",
    ),

)


/**
 * Names the generated tier resolved that the hand-written entries had never
 * heard of.
 *
 * Every one of these is a plant a curated entry already covers properly, under
 * a name that entry does not recognise: an old botanical synonym, or a common
 * name from somewhere else. Without them, dropping the duplicate generated
 * entry would have made the old name unsearchable - which is exactly what a
 * plant label bought five years ago still says.
 *
 * Keyed by [SpeciesCare.name] in [curatedSpeciesCatalogue].
 */
val bundledAliasesForCurated: Map<String, List<String>> = mapOf(


    "Air plant" to listOf(
        "blue flowered torch",
        "tillandsia lindenii",
    ),

    "Aloe vera" to listOf(
        "agave americana",
        "aloe aborescens",
        "aloe brevifolia",
        "american aloe",
        "brevifolia aloe",
        "candelabra plant",
        "century plant",
        "maguey",
        "medicine plant",
        "variegated century plant",
    ),

    "Anthurium" to listOf(
        "anthurium clarinervium",
        "anthurium hookeri",
        "anthurium scherzeranum",
        "birds nest anthurium",
        "dwarf crystal anthurium",
    ),

    "Aralia" to listOf(
        "dizygotheca elegantissima",
        "false aralia",
        "fatsia japonica",
        "japanese aralia",
        "plerandra elegantissima",
        "polyscias balfouriana",
        "polyscias fruticosa",
        "variegated balfour aralia",
    ),

    "Areca palm" to listOf(
        "chrysalidocarpus lutescens",
        "dypsis lutescens",
    ),

    "Asparagus fern" to listOf(
        "asparagus densiflorus",
        "asparagus grass",
        "climbing asparagus",
        "lace fern",
        "or ferny asparagus",
        "plume asparagus",
    ),

    "Baby tears" to listOf(
        "soleirolia soleirolii",
    ),

    "Begonia" to listOf(
        "begonia cubensis",
        "begonia haageana",
        "begonia metallica",
        "begonia president",
        "begonia semperflorens",
        "cuban holly",
        "dieffenbachia maculata",
        "dieffenbachia seguine",
        "metallic leaf begonia",
        "spotted dumb cane",
        "wax begonia",
    ),

    "Boston fern" to listOf(
        "nephrolepis exaltata",
    ),

    "Cactus" to listOf(
        "astrophytum ornatum",
        "cereus peruvianus",
        "corncob cactus",
        "echinocereus reichenbachii",
        "euphorbia mammillaris",
        "grusonia vilis",
        "lace cactus",
        "little tree cactus",
        "opuntia vilis",
        "peruvian apple cactus",
        "the bishops cap or monks hood cactus",
    ),

    "Calathea" to listOf(
        "calathea insignis",
        "calathea micans",
        "calathea roseopicta",
        "goeppertia makoyana",
        "goeppertia micans",
        "goeppertia roseopicta",
        "maranta bicolor",
        "maranta leuconeura",
        "miniature maranta",
        "peacock plant",
        "red nerve plant",
        "rose calathea",
    ),

    "Chinese evergreen" to listOf(
        "aglaonema modestum",
        "silver queen",
    ),

    "Christmas cactus" to listOf(
        "schlumbergera bridgesii",
        "schlumbergera russeliana",
        "schlumbergera truncata",
        "zygocactus truncatus",
    ),

    "Coleus" to listOf(
        "candle plant",
        "coleus australis",
        "coleus scutellarioides",
        "plectranthus australis",
        "swedish ivy",
    ),

    "Croton" to listOf(
        "codiaeum variegatum",
    ),

    "Dracaena" to listOf(
        "dracaena deremensis",
        "dracaena fragrans",
        "gold dust dracaena",
        "janet craig",
        "warneckii",
    ),

    "Fiddle leaf fig" to listOf(
        "dwarf fiddle leaf fig",
        "ficus willdemaniana",
    ),

    "Fittonia" to listOf(
        "fittonia verschaffeltii",
        "silver nerved fittonia",
    ),

    "Hoya" to listOf(
        "hoya carnosa",
        "sweetheart hoya",
    ),

    "Ivy" to listOf(
        "algerian ivy",
        "cissus alata",
        "cissus rhombifolia",
        "cissus striata",
        "clematicissus striata",
        "grape leaf ivy",
        "hedera canariensis",
        "ivy geranium",
        "miniature grape ivy",
        "pelargoniium peltatum",
    ),

    "Jade plant" to listOf(
        "arabs turban",
        "crassula argentea",
        "crassula barklyi",
        "crassula exilis",
        "crassula falcata",
        "crassula hemisphaerica",
        "crassula lycopodioides",
        "crassula muscosa",
        "crassula perfoliata",
        "crassula schmidtii",
        "crassula teres",
        "propeller plant",
        "rattlesnake tail",
        "red flowering crassula",
        "toy cypress",
    ),

    "Kalanchoe" to listOf(
        "christmas kalanchoe",
        "dwarf purple kalanchoe",
        "kalanchoe blossfeldiana",
        "kalanchoe pumila",
        "kalanchoe tomentosa",
        "panda plant",
    ),

    "Maidenhair fern" to listOf(
        "adiantum raddianum",
    ),

    "Money plant (Pilea)" to listOf(
        "aluminum plant",
        "artillery plant",
        "pilea cadierei",
        "pilea microphylla",
    ),

    "Monstera" to listOf(
        "florida",
        "monstera obliqua",
        "monstera pertusa",
        "window leaf",
    ),

    "Orchid" to listOf(
        "epidendrum atropurpureum",
        "epiphyllum",
        "orchid cacti",
        "spice orchid",
    ),

    "Oxalis" to listOf(
        "finger oxalis",
        "oxalis articulata",
        "oxalis flava",
        "oxalis rubra",
        "red oxalis",
    ),

    "Peace lily" to listOf(
        "mauna loa",
    ),

    "Peperomia" to listOf(
        "emerald ripple",
        "leather peperomia",
        "peperomia caperata",
        "peperomia crassifolia",
        "peperomia fernandopoiana",
    ),

    "Philodendron" to listOf(
        "fiddle leaf philodendron",
        "philodendron bipennifolium",
        "philodendron scandens",
        "philodendron selloum",
        "selloum",
        "thaumatophyllum bipinnatifidum",
    ),

    "Pothos" to listOf(
        "epipremnum aureum",
        "scindapsus aureus",
        "scindapsus pictus",
        "silver pothos",
    ),

    "Spider plant" to listOf(
        "chlorophytum comosum",
        "variegated spider plant",
    ),

    "String of hearts" to listOf(
        "ceropegia woodii",
    ),

    "Succulents" to listOf(
        "clipped window plant",
        "echeveria agavoides",
        "echeveria elegans",
        "haworthia truncata",
        "mexican snowball",
        "molded wax",
    ),

    "Syngonium" to listOf(
        "nephthytis",
        "syngonium podophyllum",
    ),

    "Tradescantia" to listOf(
        "billbergia zebrina",
        "callisia elegans",
        "callisia gentlei",
        "flowering inch plant",
        "purple heart",
        "setcreasea pallida",
        "striped inch plant",
        "tradescantia blossfeldiana",
        "tradescantia pallida",
        "tradescantia sillamontana",
        "tradescantia zebrina",
        "wandering jew",
        "white velvet",
        "zebra plant",
        "zebrina pendula",
    ),

)
