"""Fetch Material Symbols Rounded as Android vector drawables.

material-icons-extended is deprecated by Google's own docs, which warn it "can
also increase the build time of your apps significantly". The app used sixteen
icons out of the thousands it ships. These are those sixteen, vendored as XML.

Outlined by default. Filled is reserved for exactly one thing - the droplet in
its logged state - so weight carries meaning instead of being the default.

Re-run only to add an icon; the output is checked in.
"""
import os, re, sys, urllib.request

OUT = "../app/src/main/res/drawable"
BASE = "https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsrounded"

# (material symbols name, android file name, variant)
ICONS = [
    ("arrow_back",        "ic_arrow_back",        "default"),
    ("arrow_forward",     "ic_arrow_forward",     "default"),
    ("add",               "ic_add",               "default"),
    ("add_a_photo",       "ic_add_a_photo",       "default"),
    ("backspace",         "ic_backspace",         "default"),
    ("broken_image",      "ic_broken_image",      "default"),
    ("lock",              "ic_lock",              "default"),
    ("lock_open",         "ic_lock_open",         "default"),
    ("more_vert",         "ic_more_vert",         "default"),
    ("notifications",     "ic_notifications",     "default"),
    ("qr_code_scanner",   "ic_qr_code_scanner",   "default"),
    ("settings",          "ic_settings",          "default"),
    ("spa",               "ic_spa",               "default"),
    ("yard",              "ic_yard",              "default"),
    # The two log actions. Outlined is the resting state for both.
    ("monitor_weight",    "ic_weight",            "default"),
    ("water_drop",        "ic_water_drop",        "default"),
    ("do_not_touch",      "ic_still_wet",         "default"),
    # The single filled icon in the app: a watering that has just been logged.
    ("water_drop",        "ic_water_drop_filled", "fill1"),
]

TEMPLATE = '''<!-- Material Symbols Rounded, {name} ({variant}). Apache 2.0.
     Generated by tools/fetch-icons.py - do not edit. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="960"
    android:viewportHeight="960"
    android:autoMirrored="{mirror}">
    <group android:translateY="960">
        <path
            android:fillColor="@android:color/white"
            android:pathData="{path}" />
    </group>
</vector>
'''

MIRRORED = {"ic_arrow_back", "ic_arrow_forward"}

os.makedirs(OUT, exist_ok=True)
for name, out, variant in ICONS:
    url = f"{BASE}/{name}/{variant}/24px.svg"
    try:
        svg = urllib.request.urlopen(url, timeout=30).read().decode()
    except Exception as e:
        print(f"FAILED {name} ({variant}): {e}", file=sys.stderr)
        sys.exit(1)
    paths = re.findall(r'<path[^>]*\bd="([^"]+)"', svg)
    if not paths:
        print(f"FAILED {name}: no path in SVG", file=sys.stderr)
        sys.exit(1)
    # The viewBox is "0 -960 960 960", so y runs -960..0. Android has no
    # negative viewport origin; translating the group by +960 is exact and
    # avoids rewriting every coordinate in the path.
    # No android:tint here. Compose's Icon() applies its own ColorFilter, and a
    # "?attr/colorControlNormal" reference needs an AppCompat theme this app
    # does not have.
    xml = TEMPLATE.format(
        name=name, variant=variant, path=" ".join(paths),
        mirror="true" if out in MIRRORED else "false",
    )
    open(f"{OUT}/{out}.xml", "w").write(xml)
    print(f"  {out}.xml  ({len(' '.join(paths))} chars)")
print(f"{len(ICONS)} icons written to {OUT}")
